### ISSUE TITLE
Failed to open Optuna's dashboard when set something attrs.

### ISSUE THREAD

**Issue by c-bata** [c-bata/goptuna#34]
The cause of this error is optuna expects the value of DB is JSON format.
So [this line](https://github.com/pfnet/optuna/blob/2aedba436845f7e9f8963cf19611c1e529988f94/optuna/storages/rdb/storage.py#L586) raise following error:

```
$ optuna dashboard --storage sqlite:///db.sqlite3 --study goptuna-libffm
[W 2019-08-15 17:50:48,694] Optuna dashboard is still highly experimental. Please use with caution!
[I 2019-08-15 17:50:48,705] Starting Bokeh server version 1.0.4 (running on Tornado 6.0.2)
[I 2019-08-15 17:50:48,709] Bokeh app running at: http://localhost:5006/dashboard
[I 2019-08-15 17:50:48,709] Starting Bokeh server with process id: 52565
[E 2019-08-15 17:50:49,205] Error running application handler <bokeh.application.handlers.script.ScriptHandler object at 0x12bb7b9b0>: Expecting value: line 1 column 1 (char 0)
File "decoder.py", line 355, in raw_decode:
raise JSONDecodeError("Expecting value", s, err.value) from None Traceback (most recent call last):
  File "/Users/a14737/src/github.com/pfnet/optuna/venv/lib/python3.7/site-packages/bokeh/application/handlers/code_runner.py", line 179, in run
    exec(self._code, module.__dict__)
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/dashboard.py", line 305, in <module>
    _run()
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/dashboard.py", line 300, in _run
    app(doc)
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/dashboard.py", line 171, in __call__
    self.study.trials  # type: Optional[List[optuna.structs.FrozenTrial]]
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/study.py", line 220, in trials
    return self.storage.get_all_trials(self.study_id)
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/storages/rdb/storage.py", line 499, in get_all_trials
    trials = self._get_all_trials_without_cache(study_id)
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/storages/rdb/storage.py", line 528, in _get_all_trials_without_cache
    return self._merge_trials_orm(trials, params, values, user_attributes, system_attributes)
  File "/Users/a14737/src/github.com/pfnet/optuna/optuna/storages/rdb/storage.py", line 586, in _merge_trials_orm
    user_attrs[user_attr.key] = json.loads(user_attr.value_json)
  File "/Users/a14737/.pyenv/versions/3.7.1/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/Users/a14737/.pyenv/versions/3.7.1/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/a14737/.pyenv/versions/3.7.1/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by c-bata** [comment]
It seems I'm misunderstanding.

```
sqlite> select * from trial_user_attributes limit 10;
trial_user_attribute_id  trial_id    key         value_json
-----------------------  ----------  ----------  ----------
1                        1           key         "value1"  
2                        1           foo         "bar"     
3                        2           key         "value1"  
4                        2           foo         "bar"     
5                        3           key         "value1"  
6                        3           foo         "bar"     
7                        4           key         "value1"  
8                        4           foo         "bar"     
9                        5           key         "value1"  
10                       5           foo         "bar"     
```
